### PR TITLE
admin archives org and edits users org and fix activate user bug

### LINKED ISSUE #97: Archiving an organisation does not affect linked primary user
Awaiting for a response from @asimonw to find out what we should do with a linked user when archiving an organisation

### PR DESCRIPTION
**Pull request by JMurphyWeb**
This should close  #97 and #100 and #117

### CODE REVIEW

**Comment by JMurphyWeb** [comment]
@nelsonic i am about to push up some additions to this. will reassign you when done.

File: server/handlers.js [hunk 1]
```diff
@@ -12,6 +12,22 @@ handlers.serveView = (viewName) => (request, reply) => reply.view(viewName);
 // what does this do and why isn't it tested?
 handlers.serveFile = (request, reply) => reply.file(request.params.path);
 
+handlers.activateAccountView = (request, reply) => {
```
Comment (nelsonic) [inline server/handlers.js]: are we still _adding_ to the `handlers.js` ...? thought we were _past_ this merge conflict magnet... 😕

**Comment by nelsonic** [comment]
@JMurphyWeb looks good. (_except for still using `handlers.js` ... please sync up with @mk4111 on fixing that._ 👍 )
❤️ ✅
